
# Global options
baseURL = "https://jiema-astro.github.io"
canonifyURLs = true
copyright = "© 2022 by Jie Ma. <a href='/privacy'>Privacy policy</a>."
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en"
theme = "barks"
title = "Jie Ma"



# Main menu
[[menu.main]]
    name = "About "
    url  = "/about"
    weight = 2
[[menu.main]]
    name = "Publications"
    url  = "/publications"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/posts"
    weight = 3



# Customization options
[params]

    [params.head]
        author = "Jie Ma"
        custom_css = ""
        description = "Hi, I'm Jie, and welcome to my website!"
        keywords = ["some", "keywords", "to", "describe", "this"]

    [params.navigation]
        show_navigation = true

    [params.footer]
        show_footer = true

    [params.typography]
        title_font = "Bree Serif"
        body_font = "Source Sans Pro"

    [params.colors]
        theme_color = "#333333"
        background_color = "#fcfbf9"
        text_color = "#333333"
        link_color = "#60c17d"

    [params.social]
        [params.social.email]
            name = "E-Mail"
            class = "fas fa-envelope"
            url = "mailto:jma@phys.ethz.ch"
            weight = 2
        #[params.social.github]
        #    name = "GitHub"
        #    class = "fab fa-github"
        #    url = ""
        #    weight = 2
        [params.social.google_scholar]
            name = "Google Scholar"
            class = "ai ai-google-scholar-square"
            url = ""
            weight = 2
        #[params.social.instagram]
        #    name = "Instagram"
        #    class = "fab fa-instagram"
        #    url = ""
        #    weight = 4
        [params.social.institution]
            name = "My institution"
            class = "fas fa-university"
            url = "https://quanz-group.ethz.ch/"
            weight = 3
        #[params.social.linkedin]
        #    name = "LinkedIn"
        #    class = "fab fa-linkedin"
        #    url = ""
        #    weight = 6
        [params.social.orcid]
            name = "ORCID iD"
            class = "fab fa-orcid"
            url = "https://orcid.org/my-orcid?orcid=0000-0003-3583-6652"
            weight = 4
        #[params.social.twitter]
        #    name = "Twitter"
        #    class = "fab fa-twitter"
        #    url = ""
        #    weight = 8



# Options for Markdown renderer
[markup]

    [markup.goldmark.renderer]
        unsafe = true
        xHTML = true

    [markup.highlight]
        style = 'dracula'
